export const sagaActions = {
    FETCH_USER_EXPENSES: 'FECTH_USER_EXPENSES',
    ADD_USER_EXPENSE: 'ADD_USER_EXPENSE',
    EXPENSE_FETCH_FAILED: 'EXPENSE_FETCH_FAILED',
    EXPENSE_ADD_FAILED: 'EXPENSE_ADD_FAILED',
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_FAILED: 'LOGIN_FAILED',
    SIGNUP_USER: 'SIGNUP_USER',
    SIGNUP_FAILED: 'SIGNUP_FAILED',
    LOGOUT_USER: 'LOGOUT_USER',
};
